config/routes.rb
Rails.application.routes.draw do
  devise_for(:users)
  root("images#index")

  get("user/sign_up", to: "users#new", as: "sign_up")
  post("user/sign_up", to: "users#create")

  get("user/sign_in", to: "sessions#new", as: "sign_in")
  post("user/sign_in", to: "sessions#create")

  get("user/sign_out", to: "sessions#destroy", as: "sign_out")

  resources("users", only: [:show])
  resources("images", only: [:new, :create, :show, :edit, :update, :destroy])
  resources("comments", only: [:create, :destroy])

  get("search", to: "search#show", as: "search")
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/bryanrite/cancancan/wiki/Defining-Abilities

    can(:read, :all)

    unless user
      can(:create, [User, :session])
    else
      if user.role?(:regular)
        can(:create, [Image, Comment])

        can([:destroy, :update], Image, uploader: user)
        can([:destroy, :update], Comment, commenter: user)
        can(:destroy, :session)
      end

      if user.role?(:admin)
        can(:manage, :all)
      end
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to(:image_owner, class_name: "Image")
  belongs_to(:commenter, class_name: "User")

  validates(:body, presence: true)
  validates(:image_owner, presence: true)

  # Amount of comments shown on each page
  self.per_page = Settings.comment.per_page
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader(:asset, ImageUploader)

  acts_as_taggable_on(:tags)

  validates(:uploader, presence: true)
  validates(:asset, presence: true)
  validates(:tag_list, presence: true)
  validates(:artist, length: { maximum: 15 })

  validate(:validate_tags)
  validate(:validate_source)

  before_save(:default_values)

  belongs_to(:uploader, class_name: "User")
  has_many(:comments, foreign_key: "image_owner_id", dependent: :destroy)

  # Amount of images shown on each page
  self.per_page = Settings.image.per_page

  def validate_tags
    if tag_list.length > Settings.image.max_tags
      errors.add(:tag_list, "Can not contain more than #{Settings.image.max_tags} tags")
    end
  end

  def validate_source
    if source
      unless source.include?("://")
        errors.add(:source, "We require an absolute link. Example: https://google.com")
      end
    end
  end

  def default_values
    # ||= isn't working when updating
    self.artist = "Unkown" if self.artist.blank?
  end
end

app/models/user.rb
require "bcrypt"

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise(:database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable)

  validates(:name, presence: true)
  validates(:email, presence: true)

  has_many(:images, foreign_key: "uploader_id", dependent: :destroy)
  has_many(:comments, foreign_key: "commenter_id", dependent: :destroy)

  ROLES = %w[regular admin]

  def role?(base_role)
    ROLES.index(base_role.to_s) <= ROLES.index(role)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery(with: :exception)

  rescue_from(CanCan::AccessDenied) do |exception|
    redirect_to(root_path, alert: exception.message)
  end

  before_action(:configure_permitted_parameters, if: :devise_controller?)

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name, :password, :remember_me) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def create
    @comment = Comment.new(comment_params)
    @comment.commenter = current_user

    if @comment.save
      redirect_to(:back, notice: "Comment Succeeded")
    else
      redirect_to(:back, notice: "Comment Failed")
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to(@comment.image_owner, notice: "Comment Destroyed")
  end

  private
    def comment_params
      params.require(:comment).permit(:body, :image_owner_id)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  load_and_authorize_resource

  def index
    @images = Image.order("created_at desc").paginate(page: params[:page])
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)

    @image.asset = params[:image][:asset]
    @image.uploader = current_user

    if @image.save
      redirect_to(image_path(@image), notice: "Uploaded Image!")
    else
      render(:new)
    end
  end

  def show
    @image = Image.find(params[:id])
    @comment = Comment.new
    @comments = @image.comments.order("created_at DESC").paginate(page: params[:page])
  end

  def edit
    @image = Image.find(params[:id])
  end

  def update
    @image = Image.find(params[:id])

    if @image.update(image_params)
      redirect_to(image_path(@image), notice: "Updated Image!")
    else
      render(:edit)
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    redirect_to(root_path, notice: "Destroyed Image")
  end

  private
    def image_params
      params.require(:image).permit(:tag_list, :artist, :source, :asset)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  authorize_resource(class: false)
  
  def show
    @images = Image.tagged_with(params[:q].split(","))
        .order("created_at desc").paginate(page: params[:page])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def show
    @user = User.find(params[:id])
    @images = @user.images.order("created_at desc").paginate(page: params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include FoundationRailsHelper::FlashHelper
end

app/helpers/images_helper.rb
module ImagesHelper
  def link_to_source(source)
    domain = source.split("://", 2)[1]
    link_to(domain, source)
  end
end

app/views/comments/_comment.html.haml
.comment
  .comment-top
    = link_to(comment.commenter.name, comment.commenter)
    = content_tag(:span, "[A]", class: "commenter-admin", title: "Admin") if comment.commenter.role == "admin"
    = content_tag(:span, "[U]", class: "commenter-uploader", title: "Uploader") if comment.commenter == @image.uploader
    = link_to("Destroy", comment, method: :delete, class: "right") if can?(:destroy, comment)
    %span (#{comment.created_at.strftime("%B %d, %Y")} - #{comment.created_at.strftime("%H:%M")})
  .comment-body= comment.body

app/views/comments/_new.html.haml
= form_for(comment, url: comments_path(comment), html: { class: "new-comment-form" }) do |f|
  = f.text_area(:body, label: "Comment")
  = f.hidden_field(:image_owner_id, value: image.id)
  = f.submit("New Comment")

app/views/images/_form.html.haml
= f.text_field(:tag_list, placeholder: "Tag One, Tag Two")
= f.text_field(:artist, placeholder: "Artist")
= f.text_field(:source, placeholder: "Source")

= image_tag(@image.asset.thumbnail.url) unless @image.asset.blank?
= f.file_field(:asset, label: "Image")
= f.hidden_field(:asset_cache)

app/views/images/_image.html.haml
.small-6.medium-3.large-2.columns.text-center.end.list-image{id: image.id.to_s}
  = link_to(image_path(image)) do
    = image_tag(image.asset.thumbnail.url)

app/views/images/edit.html.haml
= form_for(@image, html: {multipart: true}) do |f|
  = link_to("Destroy", @image, method: :delete, class: "button alert")
  = render(partial: "form", locals: {f: f})
  = f.submit("Update Image!")
  = link_to("Back", @image, class: "small radius warning button")

app/views/images/index.html.haml
.large-12.columns
  - @images.each_slice(6) do |grouped_images|
    = render(grouped_images)
.large-12.columns
  = will_paginate(@images, renderer: FoundationPagination::Rails)

app/views/images/new.html.haml
= form_for(@image, url: images_path, html: {multipart: true}) do |f|
  = render(partial: "form", locals: {f: f})
  = f.submit("Upload Image!")

app/views/images/show.html.haml
#image-info.large-3.columns
  %section#image-details
    %h2 Details
    %ul
      %li Uploader: #{link_to(@image.uploader.name, user_path(@image.uploader))}
      %li Artist: #{@image.artist}
      / Display time as May 13, 2014
      %li Created: #{@image.created_at.strftime("%B %d, %Y")}
      %li Updated: #{@image.updated_at.strftime("%B %d, %Y")}
      - if @image.source
        %li Source: #{link_to_source(@image.source)}
  %section#image-tags
    %h2 Tags
    %ul
      - @image.tag_list.each do |tag|
        %li= link_to(tag, search_path(q: tag))
  = link_to("Edit Image", edit_image_path(@image), class: "small button") if can?(:edit, @image)
#image-container.large-9.columns.text-center
  = image_tag(@image.asset.url)
#comments-container.large-12.columns
  = render(partial: "comments/new", locals: {image: @image, comment: @comment})
  = render(@comments)
  = will_paginate(@comments, renderer: FoundationPagination::Rails)

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Image Board"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    .contain-to-grid
      %nav#navbar.top-bar{"data-topbar" => ""}
        %ul.title-area
          %li.name
            %h1= link_to("Image Board", root_path)
          %li.toggle-topbar.menu-icon
            %a{:href => "#"}
              %span Menu
        %section.top-bar-section
          %ul.left
            %li= link_to("Upload Image", new_image_path)
          %ul.right
            / Search form
            %li.has-form
              = form_tag(search_path, method: "get") do
                .row.collapse
                  .large-8.small-9.columns
                    = text_field_tag("q", params[:q], placeholder: "Tag One, Tag Two")
                  .large-4.small-3.columns
                    = submit_tag("Search", name: nil, class: "alert button expand")
            - if current_user
              %li= link_to("Profile", user_path(current_user))
              %li= link_to("Sign Out", destroy_user_session_path, method: :delete)
            - else
              %li= link_to("Sign In", new_user_session_path)
              %li= link_to("Sign Up", new_user_registration_path)
    .row
      = display_flash_messages
      = yield
    = javascript_include_tag "application"

app/views/search/show.html.haml
.large-12.columns
  - @images.each_slice(6) do |grouped_images|
    = render(grouped_images)
.large-12.columns
  = will_paginate(@images, renderer: FoundationPagination::Rails)

app/views/users/show.html.haml
.large-12.columns
  %h1= @user.name
%hr/
.large-12.columns
  - @images.each_slice(6) do |grouped_images|
    = render(grouped_images)
.large-12.columns
  = will_paginate(@images, renderer: FoundationPagination::Rails)